package com.example.complexeSportif.entities;

import com.example.complexeSportif.user.User;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table(name = "courses")
public class Courses {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    private String name;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date dateCourse;

    private double duration;

    @ManyToOne
    @JoinColumn(name = "user_id") // This maps to the trainer field in the database
    private User trainer;

    @ManyToOne
    @JoinColumn(name = "salle_muscu_id") // This maps to the salleMuscu field in the database
    private SalleMuscu salleMuscu;

    // Getters and setters for other fields (name, dateCourse, duration) are auto-generated by Lombok @Data
}


