spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/complexeSportif?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: localhost
    port: 1025
    username: sami
    password: sami
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
      refresh-token:
        expiration: 604800000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8082

  openai:
   model: gpt-3.5-turbo
   api:
      key: sk-proj-gUa0YityBAHRQk4xP8yzT3BlbkFJ3FqaTqzj71kxiw9x0QpD
      url: https://api.openai.com/v1/chat/completions